Add: Serializers Feature
vedovelli/miragejs-starter-kit pull request #4
Opened 2021-05-09 00:44 UTC by getJv

## Actions log

- Adding Serializers Feature
- Importing Serializers to server.
- Adding Serializers documentation

## Serializers Response Preview

<img src="https://media.giphy.com/media/IiCnJUuvGyBLAuQ8VF/source.gif"/>

2021-05-17 15:57 UTC, vedovelli commented on serializers/index.js
> + * Mirage JS guide on Models: https://miragejs.com/docs/data-layer/models
Please update this line:

```
Mirage JS guide on Serializers: https://miragejs.com/docs/main-concepts/serializers/
```

2021-05-17 15:57 UTC, vedovelli commented on serializers/index.js
> +    include: ['messages'],
Question: if a serializer is global, then why do we set messages here, given messages belong to an user and only to that entity?

2021-05-17 15:58 UTC, vedovelli requested changes
@getJv Great work! Thanks for this PR!

please check my comment/question and let me know if they are unclear!

2021-05-20 02:11 UTC, getJv commented on serializers/index.js
> + * Mirage JS guide on Models: https://miragejs.com/docs/data-layer/models
Did it.

2021-05-20 02:11 UTC, getJv commented on serializers/index.js
> +    include: ['messages'],
That is was a good observation!

If you run some tests you will realize that without `include: ['messages']` the user objects will include only the messages ids that belong to it. But if you add the `include: ['messages']` now the object messages will be attached and not only their Ids.

Is the same thing with `embed: true,` attribute. If true we have nested objects, if not siblings

2025-03-12 23:02 UTC, getJv commented
i snow a bit old proposal. im closing this PR.

2025-03-12 23:02 UTC, closed without merging